name: Build 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v1

    - name: install node
      uses: actions/setup-node@v1

    - name: install npm deps
      run: npm ci

    - name: install rust nightly
      run: rustup toolchain install nightly

    - name: make nightly the default
      run: rustup default nightly

    - name: add rust target
      run: rustup target add wasm32-unknown-unknown

    - name: build for release 
      run: npm run build 

    - name: deploy to gh_pages
      uses: maxheld83/ghpages@master
      env:
        BUILD_DIR: "public/"
        GH_PAT: ${{ secrets.GH_PAT }}
